AY2425S2-CS2103-F08-4/tp

docs/AboutUs.md

[#17] Update Brian AboutUs

---

docs/DeveloperGuide.md

Resolves #41. You are welcome to contribute more non-functional requirements.

[#41] Add non-functional requirements

---

docs/DeveloperGuide.md

[#36] Add Miscellaneous related use cases to developer guide

---

docs/DeveloperGuide.md

[#37] Add Event handling related use cases to developer guide

---

docs/DeveloperGuide.md

[#34] Add Contacts handling related use cases to developer guide

---

docs/DeveloperGuide.md

[#33] Add data handling related use cases to `DeveloperGuide.md`

---

docs/DeveloperGuide.md

[#42] Add glossary and standardize UCs 

---

src/main/java/seedu/address/logic/commands/todo/DeleteTodoCommand.java
src/main/java/seedu/address/logic/parser/todo/DeleteTodoCommandParser.java
src/main/java/seedu/address/logic/parser/todo/TodoParser.java

Resolves #78
Command: `todo delete <index>`

[#78] Add command to delete a todo

---

src/main/java/seedu/address/logic/commands/todo/DisplayTodoInformationCommand.java
src/main/java/seedu/address/logic/parser/todo/DisplayTodoInfoCommandParser.java
src/main/java/seedu/address/logic/parser/todo/TodoParser.java

Resolves #80
Command: `todo info <index>`

[#80] Add command to display a todo's information

---

src/main/java/seedu/address/MainApp.java
src/main/java/seedu/address/logic/commands/todo/AddTodoCommand.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/todo/TodoManagerWithFilteredList.java
src/test/java/seedu/address/logic/commands/person/AddPersonCommandIntegrationTest.java
src/test/java/seedu/address/logic/commands/person/ClearPersonCommandTest.java
src/test/java/seedu/address/logic/commands/person/DeletePersonCommandTest.java
src/test/java/seedu/address/logic/commands/person/EditPersonCommandTest.java
src/test/java/seedu/address/logic/commands/person/FindPersonCommandTest.java
src/test/java/seedu/address/logic/commands/person/InfoPersonCommandTest.java
src/test/java/seedu/address/logic/commands/person/ListPersonCommandTest.java
src/test/java/seedu/address/model/ModelManagerTest.java

[#89][#97] Fix Todo typos in example command and class name

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/TodoMessages.java
src/main/java/seedu/address/logic/commands/todo/AddPersonToTodoCommand.java
src/main/java/seedu/address/logic/commands/todo/AddTodoCommand.java
src/main/java/seedu/address/logic/commands/todo/DeleteTodoCommand.java
src/main/java/seedu/address/logic/commands/todo/DisplayTodoInformationCommand.java
src/main/java/seedu/address/logic/commands/todo/MarkTodoAsDoneCommand.java
src/main/java/seedu/address/logic/commands/todo/MarkTodoAsNotDoneCommand.java
src/main/java/seedu/address/logic/commands/todo/RemovePersonFromTodoCommand.java
src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/logic/parser/event/AddEventCommandParser.java
src/main/java/seedu/address/logic/parser/person/AddPersonCommandParser.java
src/main/java/seedu/address/logic/parser/todo/AddPersonToTodoCommandParser.java
src/main/java/seedu/address/logic/parser/todo/AddTodoCommandParser.java
src/main/java/seedu/address/logic/parser/todo/MarkTodoAsDoneCommandParser.java
src/main/java/seedu/address/logic/parser/todo/MarkTodoAsNotDoneCommandParser.java
src/main/java/seedu/address/logic/parser/todo/RemovePersonFromTodoCommandParser.java
src/main/java/seedu/address/logic/parser/todo/TodoParser.java
src/main/java/seedu/address/model/todo/Todo.java
src/main/java/seedu/address/model/todo/TodoStatus.java

`todo mark <index>` for marking as done.
`todo unmark <index>` for marking as not done.
Also refactor common todo related messages.
Fixes #102

[#102] Add commands to mark todos as done or not done

---

src/main/java/seedu/address/logic/commands/person/AddPersonCommand.java
src/main/java/seedu/address/logic/commands/person/DeletePersonCommand.java
src/main/java/seedu/address/logic/commands/person/EditPersonCommand.java
src/main/java/seedu/address/logic/commands/person/FilterPersonCommand.java
src/main/java/seedu/address/logic/commands/person/FindPersonCommand.java
src/main/java/seedu/address/logic/commands/person/InfoPersonCommand.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/logic/parser/person/AddPersonCommandParser.java
src/main/java/seedu/address/logic/parser/person/EditPersonCommandParser.java
src/main/java/seedu/address/logic/parser/person/FilterPersonCommandParser.java
src/main/java/seedu/address/logic/parser/person/PersonCliSyntax.java
src/main/java/seedu/address/logic/parser/person/PersonParseUtil.java
src/main/java/seedu/address/logic/parser/person/PersonParser.java
src/test/java/seedu/address/logic/LogicManagerTest.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/parser/ParserImplTest.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java
src/test/java/seedu/address/logic/parser/person/AddPersonCommandParserTest.java
src/test/java/seedu/address/logic/parser/person/EditPersonCommandParserTest.java
src/test/java/seedu/address/logic/parser/person/FilterPersonCommandParserTest.java
src/test/java/seedu/address/logic/parser/person/PersonParserTest.java
src/test/java/seedu/address/testutil/PersonUtil.java

`add...`, `find...`, `list`... --> `contact add...`, `contact find...`, `contact list`...
Resolves #55

[#55] Update contact related command strings format to use contact command word

---

build.gradle
src/main/resources/view/MainWindow.fxml

[#118] Rename AB3 to TutorConnect

---

build.gradle

[#163] Support assertion

---

src/main/java/seedu/address/logic/commands/create/AddContactCommand.java
src/main/java/seedu/address/logic/commands/create/AddEventCommand.java
src/main/java/seedu/address/logic/commands/create/AddTodoCommand.java
src/main/java/seedu/address/logic/commands/read/FilterContactCommand.java
src/main/java/seedu/address/logic/commands/read/FilterEventCommand.java
src/main/java/seedu/address/logic/commands/read/FilterTodoCommand.java
src/main/java/seedu/address/logic/commands/update/AddContactToEventCommand.java
src/main/java/seedu/address/logic/commands/update/AddContactToLogEventCommand.java
src/main/java/seedu/address/logic/commands/update/AddContactToTodoCommand.java
src/main/java/seedu/address/logic/commands/update/AddTagToContactCommand.java
src/main/java/seedu/address/logic/commands/update/AddTagToEventCommand.java
src/main/java/seedu/address/logic/commands/update/AddTagToTodoCommand.java
src/main/java/seedu/address/logic/commands/update/EditContactCommand.java
src/main/java/seedu/address/logic/commands/update/EditEventCommand.java
src/main/java/seedu/address/logic/commands/update/EditTodoCommand.java
src/main/java/seedu/address/logic/commands/update/RemoveContactFromEventCommand.java
src/main/java/seedu/address/logic/commands/update/RemoveContactFromLogEventCommand.java
src/main/java/seedu/address/logic/commands/update/RemoveContactFromTodoCommand.java
src/main/java/seedu/address/logic/commands/update/RemoveTagFromContactCommand.java
src/main/java/seedu/address/logic/commands/update/RemoveTagFromEventCommand.java
src/main/java/seedu/address/logic/commands/update/RemoveTagFromTodoCommand.java
src/main/java/seedu/address/logic/parser/contact/ContactCliSyntax.java
src/main/java/seedu/address/logic/parser/contact/ContactParser.java
src/main/java/seedu/address/logic/parser/event/EventCliSyntax.java
src/main/java/seedu/address/logic/parser/event/EventParser.java
src/main/java/seedu/address/logic/parser/todo/TodoCliSyntax.java
src/main/java/seedu/address/logic/parser/todo/TodoParser.java

[#218] Enforce space between prefix and value

---

src/test/java/seedu/address/logic/commands/delete/ClearContactCommandTest.java
src/test/java/seedu/address/logic/commands/delete/DeleteContactCommandTest.java
src/test/java/seedu/address/logic/commands/update/EditContactCommandTest.java

[#233] Add integration tests

---

src/main/java/seedu/address/MainApp.java
src/main/java/seedu/address/logic/commands/update/EditEventCommand.java
src/main/java/seedu/address/logic/commands/update/EditTodoCommand.java
src/main/java/seedu/address/logic/parser/event/EditEventCommandParser.java
src/main/java/seedu/address/logic/parser/todo/EditTodoCommandParser.java

[#244] Fix bugs for edit commands

---

docs/UserGuide.md

[#257] Update misc features in UG

---

docs/DeveloperGuide.md
docs/diagrams/CommandProposed.puml
docs/diagrams/DeleteSequenceDiagram.puml
docs/diagrams/LogicClassDiagram.puml
docs/diagrams/ParserClasses.puml
src/main/java/seedu/address/MainApp.java

Fixes #263 
also updates to 1.5.1

Update logic in DG

---

src/main/java/seedu/address/logic/parser/contact/EditContactCommandParser.java
src/main/java/seedu/address/logic/parser/contact/FilterContactCommandParser.java
src/main/java/seedu/address/logic/parser/event/EditEventCommandParser.java
src/main/java/seedu/address/logic/parser/event/FilterEventCommandParser.java
src/main/java/seedu/address/logic/parser/todo/EditTodoCommandParser.java
src/main/java/seedu/address/logic/parser/todo/FilterTodoCommandParser.java
src/main/java/seedu/address/storage/contact/JsonAdaptedContact.java
src/main/java/seedu/address/storage/event/JsonAdaptedEvent.java
src/main/java/seedu/address/storage/todo/JsonAdaptedTodo.java

[#242] Refactor long methods

---

src/main/java/seedu/address/logic/EventMessages.java
src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/read/FilterContactCommand.java
src/main/java/seedu/address/logic/commands/read/FilterEventCommand.java
src/main/java/seedu/address/logic/commands/read/FilterTodoCommand.java
src/main/java/seedu/address/logic/commands/update/AddContactToLogEventCommand.java
src/main/java/seedu/address/logic/commands/update/RemoveContactFromEventCommand.java
src/main/java/seedu/address/logic/commands/update/RemoveContactFromLogEventCommand.java
src/main/java/seedu/address/logic/commands/update/RemoveContactFromTodoCommand.java
src/main/java/seedu/address/model/contact/Course.java
src/main/java/seedu/address/model/contact/Email.java
src/main/java/seedu/address/model/contact/Group.java
src/main/java/seedu/address/model/contact/Id.java
src/main/java/seedu/address/model/item/commons/Datetime.java
src/main/java/seedu/address/model/item/commons/Location.java
src/main/java/seedu/address/model/item/commons/Name.java
src/main/java/seedu/address/model/item/commons/Tag.java
src/test/java/seedu/address/model/contact/EmailTest.java

[#346] QOL improvements

---

docs/DeveloperGuide.md

[#349] DG everything else
